name: 'Sign'
description: 'Sign files with certificates'

inputs:
  file:
    description: Files to sign
    required: true
  certificate:
    description: Certificate file
    required: true
  password:
    description: Certificate password
    required: true


runs:
  using: composite

  steps:
    # .NET is required
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.x'

    # Install the code signing tool    
    - name: Install Sign CLI tool
      run: dotnet tool install --tool-path . --prerelease sign
      shell: bash

    - name: Write PFX to file
      run: |
        printf '%s' '${{ inputs.certificate }}' > CustomSign.b64.pfx
      shell: bash

    - name: Get fingerprint
      id: fingerprint-linux
      if: runner.os == 'Linux'
      run: |
        sed '/-----/d' CustomSign.b64.pfx | base64 -d > CustomSign.pfx
        openssl pkcs12 -in CustomSign.pfx -passin pass:${{ inputs.password }} -nokeys -clcerts | openssl x509 -noout -fingerprint -sha256 >> fingerprint.txt
        sed -i 's/sha256 Fingerprint=/fingerprint=/g' fingerprint.txt
        sed -i 's/://g' fingerprint.txt
        cat fingerprint.txt >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Get fingerprint
      id: fingerprint-windows
      if: runner.os == 'Windows'
      run: |
        certutil -decode CustomSign.b64.pfx CustomSign.pfx
        openssl pkcs12 -in CustomSign.pfx -passin pass:${{ inputs.password }} -nokeys -clcerts | openssl x509 -noout -fingerprint -sha256 >> fingerprint.txt
        (Get-Content fingerprint.txt) -replace 'SHA256 Fingerprint=', 'fingerprint=' -replace ':', '' -replace '\.', '' | Set-Content fingerprint.txt
        Get-Content fingerprint.txt | Add-Content -Path $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Sign file (WIN)
      if: runner.os == 'Windows'
      run: ./sign code certificate-store ${{ inputs.file }} -cf "${{ github.workspace }}/CustomSign.pfx" -p ${{ inputs.password }} -cfp ${{ steps.fingerprint-windows.outputs.fingerprint }} -v None
      shell: bash

    - name: Sign file (LIN)
      if: runner.os == 'Linux'
      run: ./sign code certificate-store ${{ inputs.file }} -cf ${{ github.workspace }}/CustomSign.pfx -p ${{ inputs.password }} -cfp ${{ steps.fingerprint-linux.outputs.fingerprint }} -v None
      shell: bash

branding:
  author: ServerEmus
  color: black
  icon: download